export const missions=[
{id:'research',label:'01 / Discovery + Contacts + Email',title:'Find buyers with a reason to care.',body:'A live job description can reveal the workflow a company is trying to fix. Find the evidence first, then the person responsible.',preview:'Find 12 B2B SaaS companies hiring for customer-support QA. Rank the evidence, identify the owner, and draft five relevant introductions.',source:'https://landing.amplemarket.com/customers/maestroqa',sourceLabel:'Research: signal-led prospecting',brief:[
'MISSION: Find potential buyers for a customer-support quality-assurance product, not a generic SaaS list. Ask for my product URL, target geography, company-size range, and exclusions first.',
'RESEARCH: Find 12 companies with an active first-party job listing mentioning support QA, conversation reviews, agent coaching, or support quality operations. Open the actual careers page. Record title, URL, date when available, and a short evidence excerpt. Exclude expired listings, agencies, and duplicates. A hiring signal suggests a need; it does not prove purchasing intent.',
'QUALIFY: Score workflow fit 0–3, source evidence 0–3, and business-owner relevance 0–2. For the best five, identify the current Head of Support, CX, or Quality and enrich available business contacts. Flag uncertain matches and missing emails.',
'DELIVER: A ranked table with company, signal, evidence link, owner, contact status, and why my product might help. Draft a distinct email under 90 words for each of the top five, referencing the actual workflow. Ask permission before sending. Do not claim a warm relationship or promise results.'
].join('\n\n')},
{id:'champions',label:'02 / Discovery + Enrichment + Email',title:'Find where your champions went.',body:'A former happy customer may now be solving the same problem somewhere new. Start from an approved relationship list, not strangers.',preview:'Check 15 approved former customer champions, verify job changes, and draft three honest reconnection notes.',source:'https://landing.amplemarket.com/customers/maestroqa',sourceLabel:'Research: champion job changes',brief:[
'MISSION: Find relevant reconnection opportunities among former customers who already know our product. Ask for an approved list of up to 15 names, former companies, public profile URLs, and relationship notes we may use.',
'VERIFY: Check current public professional roles and employers. Match identity using at least two fields, such as profile URL and employment history. Exclude ambiguous identities. Record source URLs and available dates; an old page disappearing does not prove a job change.',
'QUALIFY: Keep people whose new role and employer still fit our product. Explain the relevant workflow at the new company, labeling inference separately from sourced facts. Retrieve only available business contact details.',
'DELIVER: A change log and three strongest reconnection candidates. Draft a note under 80 words acknowledging the real prior relationship and asking whether the problem exists in their new team. No fabricated endorsements or claims of intent. Get recipient and message approval before sending. Respect prior opt-outs.'
].join('\n\n')},
{id:'suppliers',label:'03 / Discovery + Voice + Email',title:'Find a supplier who can actually deliver.',body:'Catalog fit is only half the answer. Have your agent confirm quantity, lead time, and the delivery date with a real person.',preview:'Source 500 printed kraft mailer boxes in Bengaluru. Call three approved suppliers and compare confirmed quotes.',source:'https://sourcing.thomasnet.com/',sourceLabel:'Research: search, evaluate, connect',brief:[
'MISSION: Source 500 custom-printed kraft mailer boxes delivered to Bengaluru. Ask for dimensions, material strength, print colors, artwork readiness, delivery deadline, and maximum landed cost.',
'SHORTLIST: Find six manufacturers or converters whose own website shows relevant capabilities. Record location, product evidence, business contacts, and manufacturer/reseller status. Do not infer stock or capacity from a catalog.',
'CALL: Ask permission to call the best three. Cap each call at three minutes with a brief transparent introduction. First confirm the exact specification and delivery date. Then ask minimum order, unit price, setup fees, tax and shipping, sample turnaround, and payment terms. Prioritize deadline and total cost if time runs short. Do not place an order or promise a deposit.',
'DELIVER: Draft a specification email requesting written confirmation; send only after approval. Compare published information, spoken claims, written quotes, and unanswered questions separately. Include original transcripts. Recommend based on confirmed constraints, not the lowest advertised price.'
].join('\n\n')},
{id:'interviews',label:'04 / Email + Scheduled video',title:'Find out what broke before they left.',body:'Ask opted-in customers about a concrete moment, not a hypothetical feature wishlist. Bring back their words and a separate evidence-based synthesis.',preview:'Run three focused, three-minute interviews with opted-in churned customers. Find the triggering event, workaround, and unresolved problem.',source:'https://www.ycombinator.com/library/Iq-how-to-talk-to-users',sourceLabel:'Research: talking to users',brief:[
'MISSION: Learn from three opted-in customers who stopped using our product. Ask for product context, approved participants, timezones, and our research question. Do not contact scraped or unapproved people.',
'ARRANGE: Draft an invitation clearly describing an AI-led research conversation, not a sales call. After approval, coordinate a time through email. Create a one-use Wikshi meeting link with a 180-second limit. Share only the guest link and keep the retrieval credential private.',
'INTERVIEW: Keep the introduction under ten seconds and confirm they are comfortable continuing. Ask about the last attempt to do the task before they stopped using us, what got in the way, and what they do now. Prioritize these three topics; use one short clarifying follow-up only if time permits. Do not pitch, defend the product, suggest answers, or ask if they would buy a hypothetical feature. End before three minutes.',
'DELIVER: Retrieve each original transcript unchanged. Separately report the triggering event, workaround, and unresolved problem with exact quotes and transcript references. Distinguish observations from interpretation. Three short calls are directional evidence, not market validation. Never invent a quote from unclear transcription.'
].join('\n\n')},
{id:'venues',label:'05 / Discovery + Voice + Email',title:'Get a real shortlist for a real event.',body:'Capacity on a website is not availability on your date. Let your agent ask the practical questions before you visit.',preview:'Find a Bengaluru venue for a 30-person AI builders dinner. Confirm availability and itemized costs with three approved venues.',brief:[
'MISSION: Find a venue for a 30-person AI builders dinner in Bengaluru. Ask for date, arrival and finish times, neighborhoods, per-person budget, dietary requirements, and private-room or microphone needs.',
'RESEARCH: Shortlist six venues from their own event pages and current business contacts. Record location, stated capacity, food options, and source links. Keep advertised facts separate from availability needing confirmation.',
'VERIFY: After I approve three venues, call each for at most 150 seconds. First ask about the exact date, time, and private seating for 30. Then clarify minimum spend, tax and service charges, menu, accessibility, noise/privacy, and AV fees. Record uncertainty honestly. Do not reserve, pay a deposit, or accept terms.',
'DELIVER: Compare confirmed availability, all-in cost or missing components, and tradeoffs. Draft an email requesting an itemized written quote and cancellation policy; send only after approval. Return original transcripts and recommend the two venues meeting the actual constraints.'
].join('\n\n')},
{id:'partners',label:'06 / Discovery + Enrichment + Email',title:'Find partners already serving your buyers.',body:'Look for an adjacent audience and a concrete joint project. A relevant integration or case study is more useful than a broad company list.',preview:'Find eight specialist agencies serving our buyer segment. Propose three evidence-backed co-selling or workshop opportunities.',brief:[
'MISSION: Find distribution partners for my B2B product. Ask for product URL, ideal buyer, geography, excluded competitors, and the partnership support I can actually provide.',
'RESEARCH: Find eight specialist consultancies, agencies, or complementary software businesses whose first-party case studies show they serve our buyer. Require a specific customer story, integration, or service page. Exclude directories, paid list placements, and direct competitors.',
'QUALIFY: Identify the shared customer problem, what we contribute, what they gain, and one realistic first experiment such as a joint workshop or referral pilot. Do not infer a relationship from a logo alone. Rank evidence of audience fit and complementary capabilities, not company size.',
'DELIVER: A sourced shortlist and three specific partnership proposals. Identify the relevant founder or partnerships lead and retrieve available business contacts. Draft an email under 100 words proposing the actual experiment, without fake familiarity or guaranteed revenue. Ask me to approve recipients and copy before outreach.'
].join('\n\n')}
];
