import {SitePage,PageSection} from '@/components/wikshi-pages/SitePage';
import {WorkflowBrief} from '@/components/wikshi-pages/WorkflowBrief';
export const metadata={title:'Docs | Wikshi'};
export default function Docs(){return <SitePage eyebrow="Documentation" title="Bring your agent." accent="We’ll bring the tools." lead="A practical guide to giving your agent contacts, email, voice, and video through x402 on Hedera." art="/wikshi/art/docs-field-guide-cutout.png">
<nav className="page-index" aria-label="Documentation sections"><a href="#quickstart">Quickstart ↘</a><a href="#status">Capabilities ↘</a><a href="#video-meetings">Meetings ↘</a><a href="#payment-flow">Payments ↘</a><a href="#safety">Responsible use ↘</a></nav>
<PageSection id="quickstart" label="01 / Get started" title="Tell your agent what you need."><p className="section-intro">Start with a mission, an approved budget, and the people your agent is allowed to contact. Wikshi supplies the capabilities. Your agent owns the plan.</p><WorkflowBrief brief="Find the right people for my brief, prepare an introduction, and recommend whether email, a phone call, or a short video meeting is the best next step."/><p style={{marginTop:20}}>Read the <a className="wikshi-text-link" href="/wikshi/skills.md">workflow skill ↗</a> or <a className="wikshi-text-link" href="/#quickstart-panel">choose your agent ↗</a>.</p></PageSection>
<PageSection id="status" label="02 / Capabilities" title="Choose the right channel."><dl className="service-spec"><div><dt>Discovery</dt><dd>Search for people and companies. Enrich available business contact details. Metered by search or lookup.</dd></div><div><dt>Email</dt><dd>An agent-owned address and inbox for sending, receiving, and following up. Metered by email usage.</dd></div><div><dt>Phone</dt><dd>Mission-led voice calls with a duration limit, status, and original transcript. Metered by call duration.</dd></div><div><dt>Video</dt><dd>Guest-facing Wikshi meeting links for live conversations. Metered by session duration.</dd></div></dl><a href="/services" className="wikshi-text-link">Explore each service ↗</a></PageSection>
<PageSection id="video-meetings" label="03 / Video meetings" title="A meeting with a mission."><p className="section-intro">Your agent arranges a time with the guest, supplies the questions, and sets a time limit of up to three minutes.</p><ol className="page-steps"><li><h3>Pay and receive the link</h3><p>The paid operation returns a guest-facing meeting URL and a separate private retrieval credential. Share only the guest link.</p></li><li><h3>Have the conversation</h3><p>The guest opens a Wikshi video call in their browser. Your agent asks the questions and gathers the information. Scheduling and invitations belong to your agent; this flow does not join external Zoom or Teams rooms.</p></li><li><h3>Retrieve the transcript</h3><p>Check session status with the private credential. Once completed, retrieve the original transcript without a second payment. Keep the transcript unchanged when presenting it as a verbatim record.</p></li></ol><details><summary>Session states</summary><p>Not started, in progress, processing, and completed distinguish the normal lifecycle. Failed and expired sessions remain explicit so the agent does not mistake missing data for a completed call.</p></details><details><summary>One-use links and private access</summary><p>A purchase is for one conversation. Close the guest session after completion while retaining authorized access to its stored transcript. A public transaction receipt is never sufficient authorization to read private conversations.</p></details></PageSection>
<PageSection id="payment-flow" label="04 / x402 on Hedera" title="Know the cost before the call."><p className="section-intro">Pay in USDC without a credit card or signup. The service quote defines the price, billing unit, maximum spend, and expiry.</p><ol className="page-steps"><li><h3>Quote and authorize</h3><p>The agent reviews the service requirements and pays the quoted ceiling through the supported x402 flow.</p></li><li><h3>Execute within the budget</h3><p>A verified payment is bound to one operation. Duration caps constrain calls and video conversations.</p></li><li><h3>Measure and reconcile</h3><p>Compute the charge from measured units and the agreed rounding rules. Return unused prepaid balance in a separate Hedera refund.</p></li><li><h3>Return the result</h3><p>Link the payment, usage, and refund status in the receipt. Use a private credential for session results.</p></li></ol><p className="docs-note">This is a prepayment-and-refund flow, not native upto authorization or continuous on-chain streaming. The calculator explains the arithmetic; the service quote determines the actual rate.</p><a href="/metering" className="wikshi-text-link">Explore metering ↗</a></PageSection>
<PageSection id="safety" label="05 / Responsible use" title="Useful access. Clear boundaries."><p>Only contact people within the user’s authority and applicable consent requirements. Ask for confirmation before sending messages or placing calls unless that scope has already been explicitly delegated. Respect opt-outs and spending limits.</p><p>Keep private messages, contacts, and transcripts off-chain. Scope each inbox and retrieval credential to its owner. Never place private credentials into public meeting invitations or payment receipts.</p><p>Retries should refer to the same operation rather than placing another call or sending a duplicate email. Preserve webhook verification, idempotency, and explicit error states in any integration.</p></PageSection>
</SitePage>}
