import {SitePage,PageSection} from '@/components/wikshi-pages/SitePage';
import {WorkflowBrief} from '@/components/wikshi-pages/WorkflowBrief';
import {TestnetSetup} from '@/components/wikshi-pages/TestnetSetup';
export const metadata={title:'Docs | Wikshi'};
export default function Docs(){return <SitePage eyebrow="Documentation" title="Bring your agent." accent="We’ll bring the tools." lead="A practical guide to giving your agent contacts, email, voice, and video through x402 on Hedera." art="https://wikshi-assets.vercel.app/art/docs-field-guide-cutout.f3b7f12a58c2.webp">
<nav className="page-index" aria-label="Documentation sections"><a href="#quickstart">Quickstart ↘</a><a href="#status">Capabilities ↘</a><a href="#video-meetings">Meetings ↘</a><a href="#payment-flow">Payments ↘</a><a href="#safety">Responsible use ↘</a></nav>
<TestnetSetup/>
<PageSection id="quickstart" label="01 / Get started" title="Tell your agent what you need."><p className="section-intro">Start with a mission, an approved budget, and the people your agent is allowed to contact. Wikshi supplies the capabilities. Your agent owns the plan, approval checks, and follow-through.</p><WorkflowBrief brief="Find the right people for my brief, prepare an introduction, and recommend whether email, a phone call, or a short video meeting is the best next step."/><p style={{marginTop:20}}>Read the <a className="wikshi-text-link" href="/wikshi/skills.md">workflow skill ↗</a> or <a className="wikshi-text-link" href="/#quickstart-panel">choose your agent ↗</a>.</p></PageSection>
<PageSection id="status" label="02 / Capabilities" title="Choose the right channel."><dl className="service-spec"><div><dt>Discovery</dt><dd>Search for people and companies. Enrich available business contact details. Metered by search or lookup.</dd></div><div><dt>Email</dt><dd>Create an inbox only when email is needed, then reuse it. Inbox creation and each send or reply are separate paid operations. Reading your inbox does not require another purchase.</dd></div><div><dt>Phone</dt><dd>Mission-led voice calls with status, an original transcript, and a focused brief. Metered by call duration.</dd></div><div><dt>Video</dt><dd>Guest-facing links for AI-led conversations of up to five minutes. Metered by actual session duration.</dd></div></dl><a href="/services" className="wikshi-text-link">Explore each service ↗</a></PageSection>
<PageSection id="video-meetings" label="03 / Video meetings" title="A meeting with a mission."><p className="section-intro">Your agent supplies a mission and up to three questions. Each new meeting has a five-minute maximum. The host asks the guest to end the call when the objectives are complete.</p><ol className="page-steps"><li><h3>Pay and receive the link</h3><p>Your agent creates and privately saves its retrieval credential before purchasing. The paid operation returns a guest-facing meeting URL; share only that link, never the credential.</p></li><li><h3>Have the conversation</h3><p>The guest opens the provider-hosted video meeting in their browser. Your agent asks the questions and gathers the information. Scheduling and invitations belong to your agent; this flow does not join external Zoom or Teams rooms.</p></li><li><h3>Retrieve the transcript</h3><p>Check session status with the private credential. Once completed, retrieve the original transcript without a second payment. Keep the transcript unchanged when presenting it as a verbatim record.</p></li></ol><details><summary>Session states</summary><p>An awaiting_guest meeting has a link but no completed conversation. Check the existing operation for running or completed status and an actual transcript. A completed meeting may still have a pending refund.</p></details><details><summary>Guest links and private access</summary><p>Scheduling is advisory and hosted links are not guaranteed strictly single-use. The five-minute payment quote expiry is not the invitation expiry. A public transaction receipt cannot unlock private conversations.</p></details></PageSection>
<PageSection id="payment-flow" label="04 / x402 on Hedera" title="Know the cost before the call."><p className="section-intro">Pay in testnet USDC or HBAR without a credit card or Wikshi signup. The service quote defines the price, billing unit, maximum spend, and expiry.</p><ol className="page-steps"><li><h3>Quote and authorize</h3><p>The agent reviews the service requirements and pays the quoted ceiling through the supported x402 flow.</p></li><li><h3>Execute within the budget</h3><p>A verified payment is bound to one operation. Phone-call budgets are billing ceilings, not automatic hangup timers. New video meetings have a five-minute provider limit. Keep both briefs focused.</p></li><li><h3>Measure and reconcile</h3><p>Compute the charge from measured units and the agreed rounding rules. Return unused prepaid balance in a separate Hedera refund.</p></li><li><h3>Return the result</h3><p>Retrieve the result, signed receipt, and current refund state. Keep checking an unresolved refund after the work completes; confirmed refunds return to the actual payer in the paid currency.</p></li></ol><p className="docs-note">This is a prepayment-and-refund flow, not native upto authorization or continuous on-chain streaming. The calculator explains the arithmetic; the service quote determines the actual rate.</p><a href="/metering" className="wikshi-text-link">Explore metering ↗</a></PageSection>
<PageSection id="recovery" label="Operation recovery" title="Continue the work, not the payment."><p>Poll the existing operation to update progress without a second charge. Research and contact lookups can be cancelled after payment and have a two-minute deadline from the payment claim. Other services can only be cancelled before a payment claim.</p><p>Cancelled, paid research is reconciled with a zero-charge receipt and refund in the paid currency. A refund due is not a confirmed refund. If a provider outcome is unknown, do not send another email or place another call automatically.</p><p>External agents should retain the original inputs, operation IDs, and next steps privately. Read the <a href="https://api.wikshi.xyz/v1/docs">API contract</a> and <a href="https://api.wikshi.xyz/v1/services">live service manifest</a> for exact schemas and availability.</p></PageSection>
<PageSection id="safety" label="05 / Responsible use" title="Useful access. Clear boundaries."><p>Only contact people within the user’s authority and applicable consent requirements. Ask for confirmation before sending messages or placing calls unless that scope has already been explicitly delegated. Respect opt-outs and spending limits.</p><p>Keep private messages, contacts, and transcripts off-chain. Scope each inbox and retrieval credential to its owner. Never place private credentials into public meeting invitations or payment receipts.</p><p>Retries should refer to the same operation rather than placing another call or sending a duplicate email. Use the public /v1 API, stable idempotency keys, and your saved credential. Hosted-chat controls are not external API endpoints.</p></PageSection>
</SitePage>}
