import {SitePage,PageSection} from '@/components/wikshi-pages/SitePage';
export const metadata={title:'Services | Wikshi'};
const services=[
 {id:'email',label:'01 / Email',title:'An inbox of its own.',body:'Give your agent an email address to send from, an inbox to receive replies, and a conversation it can pick up again.',input:'Recipient, subject, message, and permission to send.',output:'Message status and replies in the agent’s inbox.',unit:'Email usage'},
 {id:'calls',label:'02 / Voice',title:'Your agent makes the call.',body:'Let your agent speak to people over the phone. Ask about availability, clarify a quote, or get the detail that is holding things up.',input:'Phone number, a focused mission, and a quoted budget.',output:'Call status, the conversation transcript, and measured usage.',unit:'Call duration'},
 {id:'meetings',label:'03 / Video',title:'A face-to-face conversation.',body:'Your agent talks to people live on scheduled Wikshi video calls. Share a meeting link, ask the right questions, and bring the answers back.',input:'Mission, questions, and a quoted session budget. Guests end the session when finished.',output:'A guest link, private retrieval credential, and original transcript.',unit:'Session duration'},
 {id:'contacts',label:'04 / Discovery',title:'Find the person to ask.',body:'Let your agent search for people and companies, then enrich business contacts before reaching out. Start with a question, not a spreadsheet.',input:'Who you are looking for, company context, and useful filters.',output:'Matching profiles and available business contact information.',unit:'Search or contact lookup'},
];
export default function Services(){return <SitePage eyebrow="Services" title="An inbox. A voice." accent="The right people to reach." lead="Useful capabilities for the agent you already use. Choose one, or connect them into a workflow. Pay per use through x402 on Hedera." art="/wikshi/art/service-toolkit-cutout.png"><nav className="page-index" aria-label="Services">{services.map(s=><a key={s.id} href={`#${s.id}`}>{s.label.slice(5)} ↘</a>)}</nav>{services.map(s=><PageSection key={s.id} id={s.id} label={s.label} title={s.title}><p className="section-intro">{s.body}</p><dl className="service-spec"><div><dt>Your agent supplies</dt><dd>{s.input}</dd></div><div><dt>Your agent gets back</dt><dd>{s.output}</dd></div><div><dt>Metered by</dt><dd>{s.unit}</dd></div></dl><a className="wikshi-text-link" href="/docs">Read the workflow ↗</a></PageSection>)}</SitePage>}
